wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713341746.592408
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 13
      - 23
      4: 3.10.13
      5: 0.16.1
      8:
      - 5
      - 9
      13: linux-x86_64
